// <auto-generated />
using System;
using FPT_Booking_BE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPT_Booking_BE.Migrations
{
    [DbContext(typeof(FptFacilityBookingContext))]
    [Migration("20251224060945_UpdateSomething")]
    partial class UpdateSomething
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FPT_Booking_BE.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AssetID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AssetType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetId")
                        .HasName("PK__Assets__434923723A6A61AA");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetId = 1,
                            AssetName = "Máy chiếu Sony 4K",
                            AssetType = "Điện tử",
                            Description = "Máy chiếu chất lượng cao"
                        },
                        new
                        {
                            AssetId = 2,
                            AssetName = "PC Gaming ROG",
                            AssetType = "Máy tính",
                            Description = "Máy tính gaming hiệu năng cao"
                        },
                        new
                        {
                            AssetId = 3,
                            AssetName = "Loa JBL Hall",
                            AssetType = "Âm thanh",
                            Description = "Hệ thống âm thanh hội trường"
                        },
                        new
                        {
                            AssetId = 4,
                            AssetName = "Điều hòa Daikin",
                            AssetType = "Điện lạnh",
                            Description = "Máy điều hòa công suất lớn"
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int")
                        .HasColumnName("ApproverID");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("BookingType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Individual");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("FacilityID");

                    b.Property<string>("PriorityLevel")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Medium");

                    b.Property<string>("Purpose")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RecurrenceGroupId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RecurrenceGroupID");

                    b.Property<int?>("RecurrencePatternId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlotId")
                        .HasColumnType("int")
                        .HasColumnName("SlotID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__73951ACD0D86927F");

                    b.HasIndex("ApproverId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("RecurrencePatternId");

                    b.HasIndex("SlotId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            BookingDate = new DateOnly(2025, 12, 24),
                            BookingType = "Individual",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FacilityId = 1,
                            PriorityLevel = "Low",
                            Purpose = "Học nhóm Java",
                            SlotId = 1,
                            Status = "Approved",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            BookingId = 2,
                            BookingDate = new DateOnly(2025, 12, 25),
                            BookingType = "Individual",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FacilityId = 2,
                            PriorityLevel = "High",
                            Purpose = "Hội thảo Tech",
                            SlotId = 2,
                            Status = "Pending",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Campus", b =>
                {
                    b.Property<int>("CampusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CampusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampusId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CampusId")
                        .HasName("PK__Campuses__FD598D3696DA5EA2");

                    b.ToTable("Campuses");

                    b.HasData(
                        new
                        {
                            CampusId = 1,
                            Address = "Lô E2a-7, Đường D1, Khu Công Nghệ Cao, Tp. Thủ Đức",
                            CampusName = "FU FPT High Tech Park",
                            IsActive = true
                        },
                        new
                        {
                            CampusId = 2,
                            Address = "04 Phạm Ngọc Thạch, Bến Nghé, Quận 1",
                            CampusName = "NVH Thanh Nien",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FacilityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int")
                        .HasColumnName("CampusID");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.HasKey("FacilityId")
                        .HasName("PK__Faciliti__5FB08B9477278C1D");

                    b.HasIndex("CampusId");

                    b.HasIndex("TypeId");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            FacilityId = 1,
                            CampusId = 1,
                            Capacity = 40,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phòng Lab AI với 40 PC Gaming",
                            FacilityName = "Lab AI - Room 302",
                            Status = "Available",
                            TypeId = 2
                        },
                        new
                        {
                            FacilityId = 2,
                            CampusId = 1,
                            Capacity = 200,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hội trường lớn cho sự kiện",
                            FacilityName = "Hội trường Beta",
                            Status = "Available",
                            TypeId = 3
                        },
                        new
                        {
                            FacilityId = 3,
                            CampusId = 1,
                            Capacity = 40,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phòng học tiêu chuẩn",
                            FacilityName = "Phòng học  - Room 300",
                            Status = "Available",
                            TypeId = 1
                        },
                        new
                        {
                            FacilityId = 4,
                            CampusId = 1,
                            Capacity = 200,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sân bóng đá mini cho sinh viên",
                            FacilityName = "Sân bóng đá mini",
                            Status = "Available",
                            TypeId = 4
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.FacilityAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("AssetID");

                    b.Property<string>("Condition")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Tốt");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("FacilityID");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK__Facility__3214EC27B673F84B");

                    b.HasIndex("AssetId");

                    b.HasIndex("FacilityId");

                    b.ToTable("FacilityAssets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetId = 1,
                            Condition = "Tốt",
                            FacilityId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            AssetId = 2,
                            Condition = "Tốt",
                            FacilityId = 1,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 3,
                            AssetId = 4,
                            Condition = "Tốt",
                            FacilityId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 4,
                            AssetId = 1,
                            Condition = "Tốt",
                            FacilityId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 5,
                            AssetId = 3,
                            Condition = "Tốt",
                            FacilityId = 2,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.FacilityType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RequiresApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypeId")
                        .HasName("PK__Facility__516F039515EF4403");

                    b.ToTable("FacilityTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            Description = "Phòng học thông thường",
                            RequiresApproval = false,
                            TypeName = "Phòng học"
                        },
                        new
                        {
                            TypeId = 2,
                            Description = "Phòng thí nghiệm",
                            RequiresApproval = true,
                            TypeName = "Phòng Lab"
                        },
                        new
                        {
                            TypeId = 3,
                            Description = "Hội trường sự kiện",
                            RequiresApproval = true,
                            TypeName = "Hội trường"
                        },
                        new
                        {
                            TypeId = 4,
                            Description = "Sân thể thao",
                            RequiresApproval = false,
                            TypeName = "Sân thể thao"
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("System");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E325A705AD8");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = false,
                            Message = "Yêu cầu Slot 1 hôm nay đã được duyệt.",
                            Title = "Đặt phòng thành công",
                            Type = "Booking",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.RecurrencePattern", b =>
                {
                    b.Property<int>("RecurrencePatternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecurrencePatternID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecurrencePatternId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DaysOfWeek")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("Interval")
                        .HasColumnType("int");

                    b.Property<int>("PatternTypeId")
                        .HasColumnType("int")
                        .HasColumnName("PatternTypeID");

                    b.Property<string>("RecurrenceGroupId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RecurrenceGroupID");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("RecurrencePatternId")
                        .HasName("PK__Recurren__PATTERN_ID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PatternTypeId");

                    b.ToTable("RecurrencePatterns");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.RecurrencePatternType", b =>
                {
                    b.Property<int>("PatternTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatternTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatternTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PatternTypeId")
                        .HasName("PK__RecurrencePatternType__ID");

                    b.ToTable("RecurrencePatternTypes");

                    b.HasData(
                        new
                        {
                            PatternTypeId = 1,
                            Description = "Repeat every day",
                            TypeName = "Daily"
                        },
                        new
                        {
                            PatternTypeId = 2,
                            Description = "Repeat every week on the same day(s)",
                            TypeName = "Weekly"
                        },
                        new
                        {
                            PatternTypeId = 3,
                            Description = "Repeat on weekdays only (Monday to Friday)",
                            TypeName = "Weekdays"
                        },
                        new
                        {
                            PatternTypeId = 4,
                            Description = "Repeat on weekends only (Saturday and Sunday)",
                            TypeName = "Weekends"
                        },
                        new
                        {
                            PatternTypeId = 5,
                            Description = "Repeat every month on the same date",
                            TypeName = "Monthly"
                        },
                        new
                        {
                            PatternTypeId = 6,
                            Description = "Custom pattern - specify which days of week",
                            TypeName = "Custom"
                        },
                        new
                        {
                            PatternTypeId = 7,
                            Description = "Repeat for the entire semester",
                            TypeName = "Semesterly"
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("FacilityID");

                    b.Property<string>("ReportType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReportId")
                        .HasName("PK__Reports__D5BD48E52C7C967E");

                    b.HasIndex("BookingId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đang code thì bị tắt máy",
                            FacilityId = 1,
                            ReportType = "Hỏng thiết bị",
                            Status = "Pending",
                            Title = "PC số 05 bị màn hình xanh",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3AB5D9A902");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B61605F36FFA0")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Quản trị viên hệ thống",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Người duyệt phòng",
                            RoleName = "FacilityAdmin"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Sinh viên",
                            RoleName = "Student"
                        },
                        new
                        {
                            RoleId = 4,
                            Description = "Giảng viên",
                            RoleName = "Lecturer"
                        },
                        new
                        {
                            RoleId = 5,
                            Description = "Quản lý thiết bị",
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 6,
                            Description = "Bảo vệ",
                            RoleName = "Security"
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.SecurityTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Normal");

                    b.Property<string>("ReportNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TaskType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TaskId")
                        .HasName("PK__Security__7C6949B1C91D2A0E");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("SecurityTasks");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SemesterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("SemesterId")
                        .HasName("PK__Semester__4BD03CA5A2A3E7B1");

                    b.ToTable("Semesters");

                    b.HasData(
                        new
                        {
                            SemesterId = 1,
                            EndDate = new DateOnly(2025, 12, 28),
                            IsActive = true,
                            Name = "Fall 2025",
                            StartDate = new DateOnly(2025, 9, 1)
                        },
                        new
                        {
                            SemesterId = 2,
                            EndDate = new DateOnly(2025, 8, 31),
                            IsActive = true,
                            Name = "Summer 2025",
                            StartDate = new DateOnly(2025, 6, 1)
                        },
                        new
                        {
                            SemesterId = 3,
                            EndDate = new DateOnly(2026, 3, 15),
                            IsActive = true,
                            Name = "Spring 2026",
                            StartDate = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            SemesterId = 4,
                            EndDate = new DateOnly(2026, 8, 31),
                            IsActive = true,
                            Name = "Summer 2026",
                            StartDate = new DateOnly(2026, 4, 1)
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Slot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SlotID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("SlotId")
                        .HasName("PK__Slots__0A124A4F26F6E8CC");

                    b.ToTable("Slots");

                    b.HasData(
                        new
                        {
                            SlotId = 1,
                            EndTime = new TimeOnly(9, 15, 0),
                            IsActive = true,
                            SlotName = "Slot 1",
                            StartTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            SlotId = 2,
                            EndTime = new TimeOnly(11, 45, 0),
                            IsActive = true,
                            SlotName = "Slot 2",
                            StartTime = new TimeOnly(9, 30, 0)
                        },
                        new
                        {
                            SlotId = 3,
                            EndTime = new TimeOnly(14, 45, 0),
                            IsActive = true,
                            SlotName = "Slot 3",
                            StartTime = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            SlotId = 4,
                            EndTime = new TimeOnly(17, 15, 0),
                            IsActive = true,
                            SlotName = "Slot 4",
                            StartTime = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            SlotId = 5,
                            EndTime = new TimeOnly(19, 45, 0),
                            IsActive = true,
                            SlotName = "Slot 5",
                            StartTime = new TimeOnly(17, 30, 0)
                        },
                        new
                        {
                            SlotId = 6,
                            EndTime = new TimeOnly(21, 0, 0),
                            IsActive = true,
                            SlotName = "Slot 6",
                            StartTime = new TimeOnly(19, 30, 0)
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACBAD4AC53");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105348CD2578C")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@fpt.edu.vn",
                            FullName = "Nguyễn Quản Trị",
                            IsActive = true,
                            PasswordHash = "123456",
                            PhoneNumber = "0901234567",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin_room@fpt.edu.vn",
                            FullName = "Lê Duyệt Phòng",
                            IsActive = true,
                            PasswordHash = "123456",
                            PhoneNumber = "0909999888",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student@fpt.edu.vn",
                            FullName = "Trần Sinh Viên",
                            IsActive = true,
                            PasswordHash = "123456",
                            PhoneNumber = "0912345678",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lecturer@fpt.edu.vn",
                            FullName = "Phạm Giảng Viên",
                            IsActive = true,
                            PasswordHash = "123456",
                            PhoneNumber = "0987654321",
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "security@fpt.edu.vn",
                            FullName = "Chú Bảo Vệ",
                            IsActive = true,
                            PasswordHash = "123456",
                            PhoneNumber = "0900000001",
                            RoleId = 6
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "s1",
                            FullName = "Sinh vien 1",
                            IsActive = true,
                            PasswordHash = "1",
                            PhoneNumber = "0900000002",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "string",
                            FullName = "Nguyễn Quản Admin",
                            IsActive = true,
                            PasswordHash = "string",
                            PhoneNumber = "0901234567",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Booking", b =>
                {
                    b.HasOne("FPT_Booking_BE.Models.User", "Approver")
                        .WithMany("BookingApprovers")
                        .HasForeignKey("ApproverId")
                        .HasConstraintName("FK__Bookings__Approv__73BA3083");

                    b.HasOne("FPT_Booking_BE.Models.Facility", "Facility")
                        .WithMany("Bookings")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__Facili__72C60C4A");

                    b.HasOne("FPT_Booking_BE.Models.RecurrencePattern", "RecurrencePattern")
                        .WithMany("Bookings")
                        .HasForeignKey("RecurrencePatternId")
                        .HasConstraintName("FK_Bookings_RecurrencePattern");

                    b.HasOne("FPT_Booking_BE.Models.Slot", "Slot")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__SlotID__74AE54BC");

                    b.HasOne("FPT_Booking_BE.Models.User", "UpdatedByNavigation")
                        .WithMany("BookingUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK_Bookings_UpdatedBy");

                    b.HasOne("FPT_Booking_BE.Models.User", "User")
                        .WithMany("BookingUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__UserID__71D1E811");

                    b.Navigation("Approver");

                    b.Navigation("Facility");

                    b.Navigation("RecurrencePattern");

                    b.Navigation("Slot");

                    b.Navigation("UpdatedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Facility", b =>
                {
                    b.HasOne("FPT_Booking_BE.Models.Campus", "Campus")
                        .WithMany("Facilities")
                        .HasForeignKey("CampusId")
                        .IsRequired()
                        .HasConstraintName("FK__Facilitie__Campu__60A75C0F");

                    b.HasOne("FPT_Booking_BE.Models.FacilityType", "Type")
                        .WithMany("Facilities")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Facilitie__TypeI__619B8048");

                    b.Navigation("Campus");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.FacilityAsset", b =>
                {
                    b.HasOne("FPT_Booking_BE.Models.Asset", "Asset")
                        .WithMany("FacilityAssets")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__FacilityA__Asset__6754599E");

                    b.HasOne("FPT_Booking_BE.Models.Facility", "Facility")
                        .WithMany("FacilityAssets")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK__FacilityA__Facil__66603565");

                    b.Navigation("Asset");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Notification", b =>
                {
                    b.HasOne("FPT_Booking_BE.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__02084FDA");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.RecurrencePattern", b =>
                {
                    b.HasOne("FPT_Booking_BE.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_RecurrencePattern_CreatedBy");

                    b.HasOne("FPT_Booking_BE.Models.RecurrencePatternType", "PatternType")
                        .WithMany("RecurrencePatterns")
                        .HasForeignKey("PatternTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_RecurrencePattern_PatternType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("PatternType");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Report", b =>
                {
                    b.HasOne("FPT_Booking_BE.Models.Booking", "Booking")
                        .WithMany("Reports")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__Reports__Booking__7C4F7684");

                    b.HasOne("FPT_Booking_BE.Models.Facility", "Facility")
                        .WithMany("Reports")
                        .HasForeignKey("FacilityId")
                        .HasConstraintName("FK__Reports__Facilit__7B5B524B");

                    b.HasOne("FPT_Booking_BE.Models.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reports__UserID__7A672E12");

                    b.Navigation("Booking");

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.SecurityTask", b =>
                {
                    b.HasOne("FPT_Booking_BE.Models.User", "AssignedToUser")
                        .WithMany("SecurityTaskAssignedToUsers")
                        .HasForeignKey("AssignedToUserId")
                        .HasConstraintName("FK_SecurityTasks_AssignedToUser");

                    b.HasOne("FPT_Booking_BE.Models.Booking", "Booking")
                        .WithMany("SecurityTasks")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_SecurityTasks_Booking");

                    b.HasOne("FPT_Booking_BE.Models.User", "CreatedByNavigation")
                        .WithMany("SecurityTaskCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_SecurityTasks_CreatedBy");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Booking");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.User", b =>
                {
                    b.HasOne("FPT_Booking_BE.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__RoleID__5AEE82B9");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Asset", b =>
                {
                    b.Navigation("FacilityAssets");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Booking", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("SecurityTasks");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Campus", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Facility", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("FacilityAssets");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.FacilityType", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.RecurrencePattern", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.RecurrencePatternType", b =>
                {
                    b.Navigation("RecurrencePatterns");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.Slot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FPT_Booking_BE.Models.User", b =>
                {
                    b.Navigation("BookingApprovers");

                    b.Navigation("BookingUpdatedByNavigations");

                    b.Navigation("BookingUsers");

                    b.Navigation("Notifications");

                    b.Navigation("Reports");

                    b.Navigation("SecurityTaskAssignedToUsers");

                    b.Navigation("SecurityTaskCreatedByNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
